apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: comments
  name: comments-svc
spec:
  ports:
  - port: 4001
    protocol: TCP
    targetPort: 4001
  selector:
    app: comments
  type: ClusterIP
status:
  loadBalancer: {}
