apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: client
  name: client-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  strategy: {}
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - image: arturops/vanilla-blog-client
        name: vanilla-blog-client
        ports:
        - containerPort: 3000
        env:
        # react app en vars need to be prefixed by REACT_APP_
        - name: REACT_APP_POSTS_DOMAIN
          value: "http://vanilla-blog.com"
        - name: REACT_APP_COMMENTS_DOMAIN
          value: "http://vanilla-blog.com"
        - name: REACT_APP_QUERY_DOMAIN
          value: "http://vanilla-blog.com"
        resources:
          limits:
            # image alone is 754 megabytes
            memory: "1000M"
            cpu: "500m"
status: {}
