apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: event-bus
  name: event-bus-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-bus
  strategy: {}
  template:
    metadata:
      labels:
        app: event-bus
    spec:
      containers:
      - image: arturops/vanilla-event-bus
        name: vanilla-event-bus
        env:
        - name: POSTS_DOMAIN
          value: "http://posts-svc"
        - name: COMMENTS_DOMAIN
          value: "http://comments-svc"
        - name: QUERY_DOMAIN
          value: "http://query-svc"
        - name: MODERATION_DOMAIN
          value: "http://moderation-svc"
        ports:
        - containerPort: 4005
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
status: {}
