apiVersion: v1
kind: Service
metadata:
  labels:
    app: event-bus
  name: event-bus-svc
spec:
  ports:
  - port: 4005
    protocol: TCP
    targetPort: 4005
  selector:
    app: event-bus
  type: ClusterIP
status:
  loadBalancer: {}
