apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: moderation
  name: moderation-svc
spec:
  ports:
  - port: 4003
    protocol: TCP
    targetPort: 4003
  selector:
    app: moderation
  type: ClusterIP
status:
  loadBalancer: {}
