apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: query
  name: query-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: query
  strategy: {}
  template:
    metadata:
      labels:
        app: query
    spec:
      containers:
      - image: arturops/vanilla-query
        name: vanilla-query
        ports:
        - containerPort: 4002
        env:
        - name: EVENT_BUS_DOMAIN
          value: "http://event-bus-svc"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
status: {}
