apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: query
  name: query-svc
spec:
  ports:
  - port: 4002
    protocol: TCP
    targetPort: 4002
  selector:
    app: query
  type: ClusterIP
status:
  loadBalancer: {}
